# Generated by Django 6.0.6 on 2026-07-04 19:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('primary_physician_name', models.CharField(blank=True, max_length=150)),
                ('primary_physician_phone', models.CharField(blank=True, max_length=30)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discharged', 'Discharged'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(blank=True, max_length=50)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('route', models.CharField(blank=True, choices=[('oral', 'Oral'), ('injection', 'Injection'), ('topical', 'Topical'), ('inhaled', 'Inhaled')], max_length=30)),
                ('prescribing_doctor', models.CharField(blank=True, max_length=150)),
                ('purpose', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('side_effects_observed', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='eldercare.resident')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=150)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('chronic', 'Chronic')], default='active', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_conditions', to='eldercare.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=150)),
                ('reaction_type', models.CharField(blank=True, max_length=150)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='eldercare.resident')),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnr_status', models.BooleanField(default=False)),
                ('living_will_on_file', models.BooleanField(default=False)),
                ('healthcare_proxy_name', models.CharField(blank=True, max_length=150)),
                ('healthcare_proxy_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advance_directive', to='eldercare.resident')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyNeedsAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('fall_risk_score', models.PositiveIntegerField(blank=True, help_text='e.g. Morse Fall Scale (0-125)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(125)])),
                ('fall_risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('fall_history_count', models.PositiveIntegerField(default=0)),
                ('last_fall_date', models.DateField(blank=True, null=True)),
                ('mobility_aid', models.CharField(blank=True, choices=[('none', 'None'), ('cane', 'Cane'), ('walker', 'Walker'), ('wheelchair', 'Wheelchair'), ('bedbound', 'Bedbound')], max_length=30)),
                ('bathing_assistance_level', models.CharField(blank=True, choices=[('independent', 'Independent'), ('partial', 'Partial'), ('full', 'Full')], max_length=20)),
                ('bathroom_grab_bars_present', models.BooleanField(default=False)),
                ('non_slip_mats_present', models.BooleanField(default=False)),
                ('cognitive_impairment_level', models.CharField(blank=True, choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('wandering_risk', models.BooleanField(default=False)),
                ('door_alarm_needed', models.BooleanField(default=False)),
                ('supervision_level_required', models.CharField(blank=True, choices=[('none', 'None'), ('periodic', 'Periodic'), ('constant', 'Constant')], max_length=20)),
                ('home_hazards_identified', models.TextField(blank=True)),
                ('bed_rail_needed', models.BooleanField(default=False)),
                ('emergency_device_present', models.BooleanField(default=False)),
                ('emergency_device_type', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_needs_assessments', to='eldercare.resident')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eldercare.staff')),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('given', 'Given'), ('missed', 'Missed'), ('refused', 'Refused')], default='given', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_logs', to='eldercare.medication')),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eldercare.staff')),
            ],
            options={
                'ordering': ['-administered_at'],
            },
        ),
        migrations.CreateModel(
            name='BasicNeedsAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('appetite_level', models.CharField(blank=True, choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good')], max_length=20)),
                ('diet_type', models.CharField(blank=True, max_length=50)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('swallowing_difficulty', models.BooleanField(default=False)),
                ('eating_assistance_level', models.CharField(blank=True, choices=[('independent', 'Independent'), ('partial', 'Partial'), ('full', 'Full')], max_length=20)),
                ('hydration_status', models.CharField(blank=True, max_length=20)),
                ('avg_fluid_intake_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('sleep_quality', models.CharField(blank=True, choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good')], max_length=20)),
                ('sleep_aid_used', models.BooleanField(default=False)),
                ('sleep_disturbances', models.TextField(blank=True)),
                ('bladder_continence', models.CharField(blank=True, choices=[('continent', 'Continent'), ('occasional', 'Occasional'), ('incontinent', 'Incontinent')], max_length=20)),
                ('bowel_continence', models.CharField(blank=True, choices=[('continent', 'Continent'), ('occasional', 'Occasional'), ('incontinent', 'Incontinent')], max_length=20)),
                ('toileting_assistance_level', models.CharField(blank=True, choices=[('independent', 'Independent'), ('partial', 'Partial'), ('full', 'Full')], max_length=20)),
                ('dressing_assistance_level', models.CharField(blank=True, choices=[('independent', 'Independent'), ('partial', 'Partial'), ('full', 'Full')], max_length=20)),
                ('grooming_assistance_level', models.CharField(blank=True, choices=[('independent', 'Independent'), ('partial', 'Partial'), ('full', 'Full')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_needs_assessments', to='eldercare.resident')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eldercare.staff')),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='TherapyNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_type', models.CharField(choices=[('physical', 'Physical'), ('occupational', 'Occupational'), ('speech', 'Speech'), ('respiratory', 'Respiratory')], max_length=50)),
                ('provider_name', models.CharField(blank=True, max_length=150)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('goals', models.TextField(blank=True)),
                ('progress_notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_needs', to='eldercare.resident')),
            ],
        ),
        migrations.CreateModel(
            name='VitalsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rate_bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('blood_oxygen_pct', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_glucose_mgdl', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eldercare.staff')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals_logs', to='eldercare.resident')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['resident', 'active'], name='eldercare_m_residen_882040_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalcondition',
            index=models.Index(fields=['resident', 'status'], name='eldercare_m_residen_4bfde2_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyneedsassessment',
            index=models.Index(fields=['resident', 'assessment_date'], name='eldercare_s_residen_834c58_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationadministrationlog',
            index=models.Index(fields=['medication', 'administered_at'], name='eldercare_m_medicat_f6e7d4_idx'),
        ),
        migrations.AddIndex(
            model_name='basicneedsassessment',
            index=models.Index(fields=['resident', 'assessment_date'], name='eldercare_b_residen_70a541_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalslog',
            index=models.Index(fields=['resident', 'recorded_at'], name='eldercare_v_residen_4b968f_idx'),
        ),
    ]
